[versions]
agp = "9.1.0"
ezxhelper = "3.2.0-preview1"
libxposed-api = "102.0.0"
dexkit = "2.0.0"
spotless = "8.10.2"

[libraries]
libxposed-api = { module = "io.github.libxposed:api", version.ref = "libxposed-api" }
ezxhelper-core = { module = "io.github.kyuubiran.ezxhelper:core", version.ref = "ezxhelper" }
dexkit = { module = "org.luckypray:dexkit", version.ref = "dexkit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
